name: UltimateAfk
version: 1.0.0-SNAPSHOT
main: main.java.me.Stefan923.SuperCore.SuperCore
description: Adds the afk status with customisable settings.
softdepend: [PlaceholderAPI]
authors: [Stefan923]

commands:
  ultimateafk:
    description: Infos about this plugin.
    aliases: [uafk]
  exit:
    description: Exits afk status.
    aliases: [ultimateafkexit, uafkexit]

permissions:
  ultimateafk.admin:
    description: Acces to powerfull commands, like /core reload.
    default: op